### ISSUE TITLE
Code for dataset split

### ISSUE THREAD

**Issue by YangJae96** [ftd-Wuchao/CCSFG#2]
Hi,

Is there a code for dataset split for market1501 and msmt17?

or should I make the code using market_sct.txt and msmt_sct.txt?

**Comment by ftd-Wuchao** [comment]
@YangJae96 
Hi! This part of the code needs to be implemented by yourself. If you have any difficulties, please feel free to contact me.

**Comment by YangJae96** [comment]
@ftd-Wuchao 

I see. 
Or could I ask for dataset download  through google drive?

It would be a great favor.

**Comment by ftd-Wuchao** [comment]
Ok, wait a minute.

**Comment by ftd-Wuchao** [comment]
@YangJae96 
Hi! You can download the dataset via the link. 
( https://drive.google.com/file/d/1Xy7whzDXZLNbabeM_oI8gwpVRfzn-OzH/view?usp=sharing )

**Comment by YangJae96** [comment]
@ftd-Wuchao 
I downloaded and checked the dataset,
I think this is the original dataset of market1501 and msmt, not sct setting used in the paper right?

For the msmt, I think the data image name does not match msmt_sct.txt.
Should I make it from the MSMT17_V2?

**Comment by YangJae96** [comment]
Dear @ftd-Wuchao 

For more detail, 

In the MSMT17/bounding_box_train that you uploaded,
the image name is as below.     -> and I think this is the original MSMT17_v1 dataset.
![image](https://user-images.githubusercontent.com/57695621/196979765-a7a730df-471a-4fd1-9a9f-353cc0c7addd.png)

But in the msmt_sct.txt, ID 0000 for example, 
0000_006_07_0303morning_0006_2.jpg
0000_007_07_0303morning_0006_2_ex.jpg
0000_008_07_0303morning_0007_2.jpg
0000_009_07_0303morning_0007_2_ex.jpg
0000_010_07_0303morning_0008_2.jpg
0000_011_07_0303morning_0009_0.jpg
0000_012_07_0303morning_0010_0.jpg

the name does not match with above images that you uploaded.

I think there should be more detail about how to make training dataset for SCT setting.
Or it would be great if you could upload the SCT setting dataset that you used for experiments.

Thanks in advance.

**Comment by ftd-Wuchao** [comment]
@YangJae96 
Hi! You can download the MSMT17 dataset for SCT setting via the link.
( https://drive.google.com/file/d/1N8rcKd494VL3ju2gB06-iP-H4cYMGVsI/view?usp=sharing )
